name: Virtualshop
favicon: null
layout_spectrum: 0.86146
typography_spectrum: 0.2851276199799031
title: Virtual Shop Online
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8125
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
