name: Virtualshop
favicon: null
layout_spectrum: 0.5271335274446756
typography_spectrum: 0.2851276199799031
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.24948580982163548
  lightness: 0.8495011625345796
  saturation: 0.7510828794911504
  rhythmicContrast: 0.5045220837928355
purpose: []
